title: "Ingo Breßler"
baseURL: "https://ibressler.github.io"
theme: "osprey-delight"
tags: ["personal", "homepage", "portfolio"]
#canonifyURLS: true
#googleAnalytics: ""
disableKinds: ["taxonomy", "taxonomyTerm", "RSS"]
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

caches:
    getjson:
        dir: ":cacheDir/:project"
        maxAge: "10h"

ignoreErrors: ["error-remote-getjson"]

module:
  imports:
    - path: github.com/hugo-mods/release-notify

## Generic theme parameters:
Params:
  author: "Ingo Breßler"
  theme: dedark

  # logoBig appears at the top of the page. Use a path relative to the assets dir for auto-resizing. 
  logoBig: "logo-large.png"

  # logoSmall is the logo that will be shown in the left corner of the nav bar.
  #   Use a path relative to the assets dir for auto-resizing.
  logoSmall: "logo-small.png"

  background: "background.jpg"

  # tagline (followed by a cursor) is shown at the top, below the logo
  #tagline: "Welcome!"

  favicon: "favicon.png"

  opengraphImage: "/images/osprey-delight.png"

  # enforceSinglePage will enforce redirection to the baseURL for all sub-directories/-pages.
  #   Example: If you create about.md, Hugo will also create a '/about/index.html'. This file will contain only a redirect directive if this switch is enabled.
  enforceSinglePage: false

  # copyright flag generates a copyright notice in footer for your site.
  copyright: true

## Social links in footer:
  Social:
  - type: twitter # the icon to use. can be anything mentioned in "assets/sass/_icons.scss" 
    url: "https://twitter.com/ingobressler"
  - type: linkedin 
    url: "https://www.linkedin.com/in/ingobressler"
  - type: xing 
    url: "https://www.xing.com/profile/Ingo_Bressler"
  - type: github
    url: "https://github.com/ibressler"
#  - type: stackoverflow  
#    url: ""

## Theme features:
  Feat:
    # useLazySizes to lazy load images with lazysizes (recommended)
    useLazySizes: true

    # ajaxBasin uses Basin for a functional contact form.
    ajaxBasin: "https://usebasin.com/f/a995a49d2fc1"

    # useStructuredData for your own https://schema.org/Person (SEO-friendly).
    #   This will be auto-generated dependent on the information you provide in this configuration.
    useStructuredData: true

    # structuredDataGitHubUser needs your USERNAME so that the GitHub API is used to fetch more information for structured data.
    #   This will use information that is publically available about your GitHub user profile at https://api.github.com/users/{USERNAME}.
    structuredDataGitHubUser: "ibressler"

    # useTermynal enables Termynal (https://github.com/ines/termynal),
    # a small JS library for showing a terminal "animation" from within your gallery item.
    # The cool thing is that the library has been stripped-down to a minimum to only have the necessary functionality.
    useTermynal: true

    googleTagManager: ""
  
  # Expert mode: Configure image resizing (some of the settings are not yet publicly documented)
  Image:
    Logo:
      resize: "300x"

    Gallery:
      resize: "400x"

    # Background:
    #   resize: "1920x"

## The menu items are automatically added to navbar. Use content files for more advanced usage.
##   See: https://gohugo.io/content-management/menus/#add-content-to-menus
Menu:
  Main:
    - name: "About"
      identifier: about # the identifier controls the section type (and therewith the appearence).
      url: "/#about"
      weight: 1
    - name: "Work"
      identifier: gallery
      url: "/#work"
      weight: 2
    - name: "Blog"
      identifier: blog
      url: "/#blog"
      weight: 3
    - name: "Contact"
      identifier: contact
      url: "/#contact"
      weight: 4
    # Use icon here to back reference an external site:
    #    - pre: "<i class='icon icon-link-ext'></i>&nbsp;"
    #      name: ""
    #      url: "https://pyotek.dev"
    #      weight: 5

defaultContentLanguage: en
# required for language switch and detection to work properly
defaultContentLanguageInSubdir: true
languages:
  en:
    weight: 1
    languageName: English
    languageCode: en-US
    # description is used in meta tags only, not visible, mdTagLine is
    description: "The Portfolio of Ingo Breßler"
    # mdTagline can be used instead to specify the tagline in Markdown for more customizability.
    #   Note that {cursor} is a placeholder and will be replaced by the actual cursor HTML when rendering.
    mdTagline: "# Welcome!\n ## This is the portfolio of Ingo Breßler{cursor}"
  de:
    weight: 2
    languageName: Deutsch
    languageCode: de-DE
    description: "Das Portfolio von Ingo Breßler"
    mdTagline: "# Willkommen!\n ## Dies ist das Portfolio von Ingo Breßler{cursor}"
